name: 编译mipsel版caddy

on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: 安装go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
      -
        name: 检查代码仓库
        uses: actions/checkout@v3
      - 
        name: 编译
        run: |
          #git clone https://github.com/caddyserver/caddy /opt/src
          tag=$(curl -s https://api.github.com/repos/caddyserver/xcaddy/releases/latest | grep -o '"tag_name": "v.*"' | cut -d'"' -f4)
          echo "xcaddy=$tag"
          rel=$(echo $tag | cut -c 2-)
          echo "xcaddy_tag=$rel"
          wget -c "https://github.com/caddyserver/xcaddy/releases/download/v$rel/xcaddy_${rel}_linux_amd64.tar.gz" -O /opt/xcaddy.tar.gz
          tar zxf /opt/xcaddy.tar.gz -C /opt/
          sudo ln -sf /opt/xcaddy_${rel}_linux_amd64/xcaddy /usr/bin/xcaddy
          xcaddy -v
          sudo chmod +x /usr/bin/xcaddy
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          mkdir -p /opt/caddy
          cd /opt/caddy
          sudo timedatectl set-timezone "Asia/Shanghai"
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          chmod 777 /opt/st/strip
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat xcaddy build
          file caddy
          du -k caddy
          cp -rf caddy caddy_upx
          /opt/st/strip caddy_upx
          /opt/upx-3.95-amd64_linux/upx --lzma --best caddy_upx
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "build_tag=$tag" >> $GITHUB_ENV
      - name: 发布Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          tag_name: ${{ env.build_tag }}
          body: |
           > ### 编译时间 ：${{ env.build_time }}

           **[官方更新说明](https://github.com/caddyserver/caddy/releases)**
          files: |
              /opt/caddy/*
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
