name: 编译mipsel版caddy

on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: 安装go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
      -
        name: 检查代码仓库
        uses: actions/checkout@v3
      - 
        name: 编译
        run: |
          git clone https://github.com/caddyserver/caddy /opt/src
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          cd /opt/src/cmd/caddy/
          sudo timedatectl set-timezone "Asia/Shanghai"
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          chmod 777 /opt/st/strip
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build
          file caddy
          du -k caddy
          mkdir -p /opt/caddy
          cp -rf caddy /opt/caddy/caddy
          cp -rf caddy /opt/caddy/caddy_upx
          cd /opt/caddy
          /opt/st/strip caddy_upx
          /opt/upx-3.95-amd64_linux/upx --lzma --best caddy_upx
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: 发布Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          tag_name: caddy
          body: |
           > ### 编译时间 ：${{ env.build_time }}

           **[官方更新说明](https://github.com/caddyserver/caddy/releases)**
          files: |
              /opt/caddy/*
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
