name: 编译mipsel版caddy

on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 运行其他流程
        uses: ./.github/workflows/编译caddy.yml
        #with:
          #canshu: v55
     # - name: 运行其他流程
       # uses: benc-uk/workflow-dispatch@v1
        #with:
         # workflow: 编译caddy.yml
